# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'FirstUsePage.ui'
##
## Created by: Qt User Interface Compiler version 6.8.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QDateEdit, QDateTimeEdit,
    QLabel, QLineEdit, QMainWindow, QMenuBar,
    QPushButton, QSizePolicy, QStatusBar, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(481, 471)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.label_Register_New_Physiotherapist = QLabel(self.centralwidget)
        self.label_Register_New_Physiotherapist.setObjectName(u"label_Register_New_Physiotherapist")
        self.label_Register_New_Physiotherapist.setGeometry(QRect(20, 10, 221, 41))
        font = QFont()
        font.setPointSize(24)
        font.setBold(True)
        self.label_Register_New_Physiotherapist.setFont(font)
        self.ResetButton = QPushButton(self.centralwidget)
        self.ResetButton.setObjectName(u"ResetButton")
        self.ResetButton.setGeometry(QRect(390, 15, 75, 24))
        self.ResetButton.setCursor(QCursor(Qt.CursorShape.OpenHandCursor))
        self.AddButton = QPushButton(self.centralwidget)
        self.AddButton.setObjectName(u"AddButton")
        self.AddButton.setGeometry(QRect(200, 390, 81, 31))
        self.AddButton.setCursor(QCursor(Qt.CursorShape.OpenHandCursor))
        self.label_Last_Name = QLabel(self.centralwidget)
        self.label_Last_Name.setObjectName(u"label_Last_Name")
        self.label_Last_Name.setGeometry(QRect(90, 270, 71, 21))
        self.lineEdit_First_Name = QLineEdit(self.centralwidget)
        self.lineEdit_First_Name.setObjectName(u"lineEdit_First_Name")
        self.lineEdit_First_Name.setGeometry(QRect(230, 230, 160, 21))
        self.lineEdit_Email = QLineEdit(self.centralwidget)
        self.lineEdit_Email.setObjectName(u"lineEdit_Email")
        self.lineEdit_Email.setGeometry(QRect(230, 70, 160, 21))
        self.comboBox_Gender = QComboBox(self.centralwidget)
        self.comboBox_Gender.addItem("")
        self.comboBox_Gender.addItem("")
        self.comboBox_Gender.addItem("")
        self.comboBox_Gender.setObjectName(u"comboBox_Gender")
        self.comboBox_Gender.setGeometry(QRect(230, 150, 160, 21))
        self.comboBox_Gender.setCursor(QCursor(Qt.CursorShape.OpenHandCursor))
        self.label_First_Name = QLabel(self.centralwidget)
        self.label_First_Name.setObjectName(u"label_First_Name")
        self.label_First_Name.setGeometry(QRect(90, 230, 71, 21))
        self.label_Email = QLabel(self.centralwidget)
        self.label_Email.setObjectName(u"label_Email")
        self.label_Email.setGeometry(QRect(90, 70, 61, 21))
        self.dateEdit_Date_Of_Birth = QDateEdit(self.centralwidget)
        self.dateEdit_Date_Of_Birth.setObjectName(u"dateEdit_Date_Of_Birth")
        self.dateEdit_Date_Of_Birth.setEnabled(True)
        self.dateEdit_Date_Of_Birth.setGeometry(QRect(230, 190, 160, 21))
        self.dateEdit_Date_Of_Birth.setCursor(QCursor(Qt.CursorShape.OpenHandCursor))
        self.dateEdit_Date_Of_Birth.setMouseTracking(False)
        self.dateEdit_Date_Of_Birth.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.dateEdit_Date_Of_Birth.setCurrentSection(QDateTimeEdit.Section.YearSection)
        self.dateEdit_Date_Of_Birth.setCalendarPopup(True)
        self.label_Date_Of_Birth = QLabel(self.centralwidget)
        self.label_Date_Of_Birth.setObjectName(u"label_Date_Of_Birth")
        self.label_Date_Of_Birth.setGeometry(QRect(90, 190, 71, 21))
        self.label_Gender = QLabel(self.centralwidget)
        self.label_Gender.setObjectName(u"label_Gender")
        self.label_Gender.setGeometry(QRect(90, 150, 49, 21))
        self.lineEdit_Last_Name = QLineEdit(self.centralwidget)
        self.lineEdit_Last_Name.setObjectName(u"lineEdit_Last_Name")
        self.lineEdit_Last_Name.setGeometry(QRect(230, 270, 160, 21))
        self.lineEdit_Password_Confirmation = QLineEdit(self.centralwidget)
        self.lineEdit_Password_Confirmation.setObjectName(u"lineEdit_Password_Confirmation")
        self.lineEdit_Password_Confirmation.setGeometry(QRect(230, 350, 160, 21))
        self.label_Password_Confirmation = QLabel(self.centralwidget)
        self.label_Password_Confirmation.setObjectName(u"label_Password_Confirmation")
        self.label_Password_Confirmation.setGeometry(QRect(90, 350, 131, 21))
        self.lineEdit_Password = QLineEdit(self.centralwidget)
        self.lineEdit_Password.setObjectName(u"lineEdit_Password")
        self.lineEdit_Password.setGeometry(QRect(230, 310, 160, 21))
        self.label_Password = QLabel(self.centralwidget)
        self.label_Password.setObjectName(u"label_Password")
        self.label_Password.setGeometry(QRect(90, 310, 71, 21))
        self.label_Username = QLabel(self.centralwidget)
        self.label_Username.setObjectName(u"label_Username")
        self.label_Username.setGeometry(QRect(90, 110, 61, 21))
        self.lineEdit_Username = QLineEdit(self.centralwidget)
        self.lineEdit_Username.setObjectName(u"lineEdit_Username")
        self.lineEdit_Username.setGeometry(QRect(230, 110, 160, 21))
        self.error_Email = QLabel(self.centralwidget)
        self.error_Email.setObjectName(u"error_Email")
        self.error_Email.setGeometry(QRect(239, 90, 200, 16))
        self.error_Username = QLabel(self.centralwidget)
        self.error_Username.setObjectName(u"error_Username")
        self.error_Username.setGeometry(QRect(239, 130, 200, 16))
        self.error_First_Name = QLabel(self.centralwidget)
        self.error_First_Name.setObjectName(u"error_First_Name")
        self.error_First_Name.setGeometry(QRect(239, 250, 200, 16))
        self.error_Last_Name = QLabel(self.centralwidget)
        self.error_Last_Name.setObjectName(u"error_Last_Name")
        self.error_Last_Name.setGeometry(QRect(239, 290, 200, 16))
        self.error_Password = QLabel(self.centralwidget)
        self.error_Password.setObjectName(u"error_Password")
        self.error_Password.setGeometry(QRect(239, 330, 200, 16))
        self.error_Password_Confirmation = QLabel(self.centralwidget)
        self.error_Password_Confirmation.setObjectName(u"error_Password_Confirmation")
        self.error_Password_Confirmation.setGeometry(QRect(239, 370, 200, 16))
        self.error_Gender = QLabel(self.centralwidget)
        self.error_Gender.setObjectName(u"error_Gender")
        self.error_Gender.setGeometry(QRect(239, 170, 200, 16))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 481, 22))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.comboBox_Gender.setCurrentIndex(-1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label_Register_New_Physiotherapist.setText(QCoreApplication.translate("MainWindow", u"First Use Page", None))
        self.ResetButton.setText(QCoreApplication.translate("MainWindow", u"Reset", None))
        self.AddButton.setText(QCoreApplication.translate("MainWindow", u"Add Admin", None))
        self.label_Last_Name.setText(QCoreApplication.translate("MainWindow", u"Last Name:", None))
        self.comboBox_Gender.setItemText(0, QCoreApplication.translate("MainWindow", u"Male", None))
        self.comboBox_Gender.setItemText(1, QCoreApplication.translate("MainWindow", u"Female", None))
        self.comboBox_Gender.setItemText(2, QCoreApplication.translate("MainWindow", u"Other", None))

        self.label_First_Name.setText(QCoreApplication.translate("MainWindow", u"First Name:", None))
        self.label_Email.setText(QCoreApplication.translate("MainWindow", u"Email:", None))
        self.label_Date_Of_Birth.setText(QCoreApplication.translate("MainWindow", u"Date Of Birth:", None))
        self.label_Gender.setText(QCoreApplication.translate("MainWindow", u"Gender:", None))
        self.label_Password_Confirmation.setText(QCoreApplication.translate("MainWindow", u"Password Confirmation:", None))
        self.label_Password.setText(QCoreApplication.translate("MainWindow", u"Password:", None))
        self.label_Username.setText(QCoreApplication.translate("MainWindow", u"Username:", None))
        self.error_Email.setText(QCoreApplication.translate("MainWindow", u"error_Email", None))
        self.error_Username.setText(QCoreApplication.translate("MainWindow", u"error_Username", None))
        self.error_First_Name.setText(QCoreApplication.translate("MainWindow", u"error_First_Name", None))
        self.error_Last_Name.setText(QCoreApplication.translate("MainWindow", u"error_Last_Name", None))
        self.error_Password.setText(QCoreApplication.translate("MainWindow", u"error_Password", None))
        self.error_Password_Confirmation.setText(QCoreApplication.translate("MainWindow", u"error_Password_Confirmation", None))
        self.error_Gender.setText(QCoreApplication.translate("MainWindow", u"error_Gender", None))
    # retranslateUi

