# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'TestParametersPage.ui'
##
## Created by: Qt User Interface Compiler version 6.8.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QDateEdit, QLabel,
    QLineEdit, QMainWindow, QMenuBar, QPushButton,
    QSizePolicy, QStatusBar, QTextEdit, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(543, 569)
        MainWindow.setCursor(QCursor(Qt.CursorShape.ArrowCursor))
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.ContinueButton = QPushButton(self.centralwidget)
        self.ContinueButton.setObjectName(u"ContinueButton")
        self.ContinueButton.setGeometry(QRect(219, 443, 101, 31))
        self.ContinueButton.setCursor(QCursor(Qt.CursorShape.OpenHandCursor))
        self.comboBox_Gender = QComboBox(self.centralwidget)
        self.comboBox_Gender.addItem("")
        self.comboBox_Gender.addItem("")
        self.comboBox_Gender.addItem("")
        self.comboBox_Gender.setObjectName(u"comboBox_Gender")
        self.comboBox_Gender.setGeometry(QRect(190, 110, 160, 21))
        self.comboBox_Gender.setCursor(QCursor(Qt.CursorShape.OpenHandCursor))
        self.label_Patient_ID = QLabel(self.centralwidget)
        self.label_Patient_ID.setObjectName(u"label_Patient_ID")
        self.label_Patient_ID.setGeometry(QRect(100, 70, 61, 21))
        self.label_Gender = QLabel(self.centralwidget)
        self.label_Gender.setObjectName(u"label_Gender")
        self.label_Gender.setGeometry(QRect(100, 110, 49, 21))
        self.label_Test_Parameters_Page = QLabel(self.centralwidget)
        self.label_Test_Parameters_Page.setObjectName(u"label_Test_Parameters_Page")
        self.label_Test_Parameters_Page.setGeometry(QRect(18, 10, 331, 41))
        font = QFont()
        font.setPointSize(24)
        font.setBold(True)
        self.label_Test_Parameters_Page.setFont(font)
        self.label_Date_Of_Birth = QLabel(self.centralwidget)
        self.label_Date_Of_Birth.setObjectName(u"label_Date_Of_Birth")
        self.label_Date_Of_Birth.setGeometry(QRect(100, 150, 71, 21))
        self.label_Pelvic_Width = QLabel(self.centralwidget)
        self.label_Pelvic_Width.setObjectName(u"label_Pelvic_Width")
        self.label_Pelvic_Width.setGeometry(QRect(100, 230, 71, 21))
        self.label_Has_Fallen = QLabel(self.centralwidget)
        self.label_Has_Fallen.setObjectName(u"label_Has_Fallen")
        self.label_Has_Fallen.setGeometry(QRect(100, 270, 211, 21))
        self.lineEdit_Patient_ID = QLineEdit(self.centralwidget)
        self.lineEdit_Patient_ID.setObjectName(u"lineEdit_Patient_ID")
        self.lineEdit_Patient_ID.setGeometry(QRect(190, 70, 160, 21))
        self.comboBox_Has_Fallen = QComboBox(self.centralwidget)
        self.comboBox_Has_Fallen.addItem("")
        self.comboBox_Has_Fallen.addItem("")
        self.comboBox_Has_Fallen.setObjectName(u"comboBox_Has_Fallen")
        self.comboBox_Has_Fallen.setGeometry(QRect(190, 300, 160, 21))
        self.comboBox_Has_Fallen.setCursor(QCursor(Qt.CursorShape.OpenHandCursor))
        self.lineEdit_Pelvic_Width = QLineEdit(self.centralwidget)
        self.lineEdit_Pelvic_Width.setObjectName(u"lineEdit_Pelvic_Width")
        self.lineEdit_Pelvic_Width.setGeometry(QRect(190, 230, 160, 21))
        self.dateEdit_Date_Of_Birth = QDateEdit(self.centralwidget)
        self.dateEdit_Date_Of_Birth.setObjectName(u"dateEdit_Date_Of_Birth")
        self.dateEdit_Date_Of_Birth.setEnabled(True)
        self.dateEdit_Date_Of_Birth.setGeometry(QRect(190, 150, 160, 21))
        self.dateEdit_Date_Of_Birth.setCursor(QCursor(Qt.CursorShape.OpenHandCursor))
        self.dateEdit_Date_Of_Birth.setMouseTracking(False)
        self.dateEdit_Date_Of_Birth.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.dateEdit_Date_Of_Birth.setCalendarPopup(True)
        self.LogOffButton = QPushButton(self.centralwidget)
        self.LogOffButton.setObjectName(u"LogOffButton")
        self.LogOffButton.setGeometry(QRect(440, 490, 75, 24))
        self.LogOffButton.setCursor(QCursor(Qt.CursorShape.OpenHandCursor))
        self.lineEdit_Shoe_Width = QLineEdit(self.centralwidget)
        self.lineEdit_Shoe_Width.setObjectName(u"lineEdit_Shoe_Width")
        self.lineEdit_Shoe_Width.setGeometry(QRect(190, 190, 160, 21))
        self.label_Shoe_Width = QLabel(self.centralwidget)
        self.label_Shoe_Width.setObjectName(u"label_Shoe_Width")
        self.label_Shoe_Width.setGeometry(QRect(100, 190, 71, 21))
        self.label_Notes = QLabel(self.centralwidget)
        self.label_Notes.setObjectName(u"label_Notes")
        self.label_Notes.setGeometry(QRect(100, 340, 71, 21))
        self.textEdit_Notes = QTextEdit(self.centralwidget)
        self.textEdit_Notes.setObjectName(u"textEdit_Notes")
        self.textEdit_Notes.setGeometry(QRect(190, 340, 160, 71))
        self.textEdit_Notes.viewport().setProperty(u"cursor", QCursor(Qt.CursorShape.IBeamCursor))
        self.AdminPageButton = QPushButton(self.centralwidget)
        self.AdminPageButton.setObjectName(u"AdminPageButton")
        self.AdminPageButton.setGeometry(QRect(20, 490, 75, 24))
        self.AdminPageButton.setCursor(QCursor(Qt.CursorShape.OpenHandCursor))
        self.CheckSystemButton = QPushButton(self.centralwidget)
        self.CheckSystemButton.setObjectName(u"CheckSystemButton")
        self.CheckSystemButton.setGeometry(QRect(229, 490, 81, 24))
        self.CheckSystemButton.setCursor(QCursor(Qt.CursorShape.OpenHandCursor))
        self.label_welcome_user = QLabel(self.centralwidget)
        self.label_welcome_user.setObjectName(u"label_welcome_user")
        self.label_welcome_user.setGeometry(QRect(330, 22, 121, 16))
        self.PatientHistoryButton = QPushButton(self.centralwidget)
        self.PatientHistoryButton.setObjectName(u"PatientHistoryButton")
        self.PatientHistoryButton.setGeometry(QRect(390, 68, 95, 24))
        self.PatientHistoryButton.setCursor(QCursor(Qt.CursorShape.OpenHandCursor))
        self.error_Patient_Id = QLabel(self.centralwidget)
        self.error_Patient_Id.setObjectName(u"error_Patient_Id")
        self.error_Patient_Id.setGeometry(QRect(199, 90, 200, 16))
        self.error_Shoe_Width = QLabel(self.centralwidget)
        self.error_Shoe_Width.setObjectName(u"error_Shoe_Width")
        self.error_Shoe_Width.setGeometry(QRect(199, 210, 300, 16))
        self.error_Pelvic_Width = QLabel(self.centralwidget)
        self.error_Pelvic_Width.setObjectName(u"error_Pelvic_Width")
        self.error_Pelvic_Width.setGeometry(QRect(199, 250, 300, 16))
        self.error_Patient_Has_Fallen = QLabel(self.centralwidget)
        self.error_Patient_Has_Fallen.setObjectName(u"error_Patient_Has_Fallen")
        self.error_Patient_Has_Fallen.setGeometry(QRect(199, 320, 300, 16))
        self.DT_Notes = QLabel(self.centralwidget)
        self.DT_Notes.setObjectName(u"DT_Notes")
        self.DT_Notes.setGeometry(QRect(360, 340, 61, 16))
        self.comboBoxLanguage = QComboBox(self.centralwidget)
        self.comboBoxLanguage.addItem("")
        self.comboBoxLanguage.addItem("")
        self.comboBoxLanguage.setObjectName(u"comboBoxLanguage")
        self.comboBoxLanguage.setGeometry(QRect(460, 20, 68, 22))
        self.comboBoxLanguage.setCursor(QCursor(Qt.CursorShape.OpenHandCursor))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 543, 22))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        QWidget.setTabOrder(self.lineEdit_Patient_ID, self.PatientHistoryButton)
        QWidget.setTabOrder(self.PatientHistoryButton, self.comboBox_Gender)
        QWidget.setTabOrder(self.comboBox_Gender, self.dateEdit_Date_Of_Birth)
        QWidget.setTabOrder(self.dateEdit_Date_Of_Birth, self.lineEdit_Shoe_Width)
        QWidget.setTabOrder(self.lineEdit_Shoe_Width, self.lineEdit_Pelvic_Width)
        QWidget.setTabOrder(self.lineEdit_Pelvic_Width, self.comboBox_Has_Fallen)
        QWidget.setTabOrder(self.comboBox_Has_Fallen, self.textEdit_Notes)
        QWidget.setTabOrder(self.textEdit_Notes, self.ContinueButton)
        QWidget.setTabOrder(self.ContinueButton, self.AdminPageButton)
        QWidget.setTabOrder(self.AdminPageButton, self.CheckSystemButton)
        QWidget.setTabOrder(self.CheckSystemButton, self.LogOffButton)

        self.retranslateUi(MainWindow)

        self.comboBox_Gender.setCurrentIndex(-1)
        self.comboBox_Has_Fallen.setCurrentIndex(-1)
        self.comboBoxLanguage.setCurrentIndex(-1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Test Parameters Page", None))
        self.ContinueButton.setText(QCoreApplication.translate("MainWindow", u"Continue", None))
        self.comboBox_Gender.setItemText(0, QCoreApplication.translate("MainWindow", u"Male", None))
        self.comboBox_Gender.setItemText(1, QCoreApplication.translate("MainWindow", u"Female", None))
        self.comboBox_Gender.setItemText(2, QCoreApplication.translate("MainWindow", u"Other", None))

        self.label_Patient_ID.setText(QCoreApplication.translate("MainWindow", u"Patient ID:", None))
        self.label_Gender.setText(QCoreApplication.translate("MainWindow", u"Gender:", None))
        self.label_Test_Parameters_Page.setText(QCoreApplication.translate("MainWindow", u"Test Parameters Page", None))
        self.label_Date_Of_Birth.setText(QCoreApplication.translate("MainWindow", u"Date Of Birth:", None))
        self.label_Pelvic_Width.setText(QCoreApplication.translate("MainWindow", u"Pelvic Width:", None))
        self.label_Has_Fallen.setText(QCoreApplication.translate("MainWindow", u"Has the patient fallen in the last year?", None))
        self.comboBox_Has_Fallen.setItemText(0, QCoreApplication.translate("MainWindow", u"Yes", None))
        self.comboBox_Has_Fallen.setItemText(1, QCoreApplication.translate("MainWindow", u"No", None))

        self.LogOffButton.setText(QCoreApplication.translate("MainWindow", u"Log Off", None))
        self.label_Shoe_Width.setText(QCoreApplication.translate("MainWindow", u"Shoe Width:", None))
        self.label_Notes.setText(QCoreApplication.translate("MainWindow", u"Notes", None))
        self.AdminPageButton.setText(QCoreApplication.translate("MainWindow", u"Admin Page", None))
        self.CheckSystemButton.setText(QCoreApplication.translate("MainWindow", u"Check System", None))
        self.label_welcome_user.setText(QCoreApplication.translate("MainWindow", u"Welcome, User's Name", None))
        self.PatientHistoryButton.setText(QCoreApplication.translate("MainWindow", u"Patient's History", None))
        self.error_Patient_Id.setText(QCoreApplication.translate("MainWindow", u"error_Patient_Id", None))
        self.error_Shoe_Width.setText(QCoreApplication.translate("MainWindow", u"error_Shoe_Width", None))
        self.error_Pelvic_Width.setText(QCoreApplication.translate("MainWindow", u"error_Pelvic_Width", None))
        self.error_Patient_Has_Fallen.setText(QCoreApplication.translate("MainWindow", u"error_Patient_Has_Fallen", None))
        self.DT_Notes.setText(QCoreApplication.translate("MainWindow", u"DT_Notes", None))
        self.comboBoxLanguage.setItemText(0, QCoreApplication.translate("MainWindow", u"English", None))
        self.comboBoxLanguage.setItemText(1, QCoreApplication.translate("MainWindow", u"\u05e2\u05d1\u05e8\u05d9\u05ea", None))

        self.comboBoxLanguage.setCurrentText("")
    # retranslateUi

