# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'FirstUsePage.ui'
##
## Created by: Qt User Interface Compiler version 6.8.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QDateEdit, QDateTimeEdit,
    QLabel, QLineEdit, QMainWindow, QMenuBar,
    QPushButton, QSizePolicy, QStatusBar, QWidget)

class Ui_FirstUsePage(object):
    def setupUi(self, FirstUsePage):
        if not FirstUsePage.objectName():
            FirstUsePage.setObjectName(u"FirstUsePage")
        FirstUsePage.resize(477, 463)
        self.centralwidget = QWidget(FirstUsePage)
        self.centralwidget.setObjectName(u"centralwidget")
        self.ResetButton = QPushButton(self.centralwidget)
        self.ResetButton.setObjectName(u"ResetButton")
        self.ResetButton.setGeometry(QRect(390, 40, 75, 24))
        self.ResetButton.setCursor(QCursor(Qt.CursorShape.OpenHandCursor))
        self.AddButton = QPushButton(self.centralwidget)
        self.AddButton.setObjectName(u"AddButton")
        self.AddButton.setGeometry(QRect(190, 390, 101, 31))
        self.AddButton.setCursor(QCursor(Qt.CursorShape.OpenHandCursor))
        self.label_Last_Name = QLabel(self.centralwidget)
        self.label_Last_Name.setObjectName(u"label_Last_Name")
        self.label_Last_Name.setGeometry(QRect(90, 270, 300, 21))
        self.lineEdit_First_Name = QLineEdit(self.centralwidget)
        self.lineEdit_First_Name.setObjectName(u"lineEdit_First_Name")
        self.lineEdit_First_Name.setGeometry(QRect(230, 230, 160, 21))
        self.lineEdit_Email = QLineEdit(self.centralwidget)
        self.lineEdit_Email.setObjectName(u"lineEdit_Email")
        self.lineEdit_Email.setGeometry(QRect(230, 70, 160, 21))
        self.comboBox_Gender = QComboBox(self.centralwidget)
        self.comboBox_Gender.addItem("")
        self.comboBox_Gender.addItem("")
        self.comboBox_Gender.addItem("")
        self.comboBox_Gender.setObjectName(u"comboBox_Gender")
        self.comboBox_Gender.setGeometry(QRect(230, 150, 160, 21))
        self.comboBox_Gender.setCursor(QCursor(Qt.CursorShape.OpenHandCursor))
        self.label_First_Name = QLabel(self.centralwidget)
        self.label_First_Name.setObjectName(u"label_First_Name")
        self.label_First_Name.setGeometry(QRect(90, 230, 300, 21))
        self.label_Email = QLabel(self.centralwidget)
        self.label_Email.setObjectName(u"label_Email")
        self.label_Email.setGeometry(QRect(90, 70, 300, 21))
        self.dateEdit_Date_Of_Birth = QDateEdit(self.centralwidget)
        self.dateEdit_Date_Of_Birth.setObjectName(u"dateEdit_Date_Of_Birth")
        self.dateEdit_Date_Of_Birth.setEnabled(True)
        self.dateEdit_Date_Of_Birth.setGeometry(QRect(230, 190, 160, 21))
        self.dateEdit_Date_Of_Birth.setCursor(QCursor(Qt.CursorShape.OpenHandCursor))
        self.dateEdit_Date_Of_Birth.setMouseTracking(False)
        self.dateEdit_Date_Of_Birth.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.dateEdit_Date_Of_Birth.setCurrentSection(QDateTimeEdit.Section.YearSection)
        self.dateEdit_Date_Of_Birth.setCalendarPopup(True)
        self.label_Date_Of_Birth = QLabel(self.centralwidget)
        self.label_Date_Of_Birth.setObjectName(u"label_Date_Of_Birth")
        self.label_Date_Of_Birth.setGeometry(QRect(90, 190, 300, 21))
        self.label_Gender = QLabel(self.centralwidget)
        self.label_Gender.setObjectName(u"label_Gender")
        self.label_Gender.setGeometry(QRect(90, 150, 300, 21))
        self.lineEdit_Last_Name = QLineEdit(self.centralwidget)
        self.lineEdit_Last_Name.setObjectName(u"lineEdit_Last_Name")
        self.lineEdit_Last_Name.setGeometry(QRect(230, 270, 160, 21))
        self.lineEdit_Password_Confirmation = QLineEdit(self.centralwidget)
        self.lineEdit_Password_Confirmation.setObjectName(u"lineEdit_Password_Confirmation")
        self.lineEdit_Password_Confirmation.setGeometry(QRect(230, 350, 160, 21))
        self.label_Password_Confirmation = QLabel(self.centralwidget)
        self.label_Password_Confirmation.setObjectName(u"label_Password_Confirmation")
        self.label_Password_Confirmation.setGeometry(QRect(90, 350, 300, 21))
        self.lineEdit_Password = QLineEdit(self.centralwidget)
        self.lineEdit_Password.setObjectName(u"lineEdit_Password")
        self.lineEdit_Password.setGeometry(QRect(230, 310, 160, 21))
        self.label_Password = QLabel(self.centralwidget)
        self.label_Password.setObjectName(u"label_Password")
        self.label_Password.setGeometry(QRect(90, 310, 300, 21))
        self.label_Username = QLabel(self.centralwidget)
        self.label_Username.setObjectName(u"label_Username")
        self.label_Username.setGeometry(QRect(90, 110, 300, 21))
        self.lineEdit_Username = QLineEdit(self.centralwidget)
        self.lineEdit_Username.setObjectName(u"lineEdit_Username")
        self.lineEdit_Username.setGeometry(QRect(230, 110, 160, 21))
        self.error_Email = QLabel(self.centralwidget)
        self.error_Email.setObjectName(u"error_Email")
        self.error_Email.setGeometry(QRect(230, 90, 200, 16))
        self.error_Username = QLabel(self.centralwidget)
        self.error_Username.setObjectName(u"error_Username")
        self.error_Username.setGeometry(QRect(230, 130, 200, 16))
        self.error_First_Name = QLabel(self.centralwidget)
        self.error_First_Name.setObjectName(u"error_First_Name")
        self.error_First_Name.setGeometry(QRect(230, 250, 200, 16))
        self.error_Last_Name = QLabel(self.centralwidget)
        self.error_Last_Name.setObjectName(u"error_Last_Name")
        self.error_Last_Name.setGeometry(QRect(230, 290, 200, 16))
        self.error_Password = QLabel(self.centralwidget)
        self.error_Password.setObjectName(u"error_Password")
        self.error_Password.setGeometry(QRect(230, 330, 200, 16))
        self.error_Password_Confirmation = QLabel(self.centralwidget)
        self.error_Password_Confirmation.setObjectName(u"error_Password_Confirmation")
        self.error_Password_Confirmation.setGeometry(QRect(230, 370, 200, 16))
        self.error_Gender = QLabel(self.centralwidget)
        self.error_Gender.setObjectName(u"error_Gender")
        self.error_Gender.setGeometry(QRect(230, 170, 200, 16))
        self.comboBoxLanguage = QComboBox(self.centralwidget)
        self.comboBoxLanguage.addItem("")
        self.comboBoxLanguage.addItem("")
        self.comboBoxLanguage.setObjectName(u"comboBoxLanguage")
        self.comboBoxLanguage.setGeometry(QRect(390, 10, 75, 22))
        self.comboBoxLanguage.setCursor(QCursor(Qt.CursorShape.OpenHandCursor))
        self.label_Register_New_Physiotherapist = QLabel(self.centralwidget)
        self.label_Register_New_Physiotherapist.setObjectName(u"label_Register_New_Physiotherapist")
        self.label_Register_New_Physiotherapist.setGeometry(QRect(20, 20, 437, 20))
        font = QFont()
        font.setPointSize(9)
        font.setBold(True)
        self.label_Register_New_Physiotherapist.setFont(font)
        FirstUsePage.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(FirstUsePage)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 477, 22))
        FirstUsePage.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(FirstUsePage)
        self.statusbar.setObjectName(u"statusbar")
        FirstUsePage.setStatusBar(self.statusbar)
        QWidget.setTabOrder(self.ResetButton, self.lineEdit_Email)
        QWidget.setTabOrder(self.lineEdit_Email, self.lineEdit_Username)
        QWidget.setTabOrder(self.lineEdit_Username, self.comboBox_Gender)
        QWidget.setTabOrder(self.comboBox_Gender, self.dateEdit_Date_Of_Birth)
        QWidget.setTabOrder(self.dateEdit_Date_Of_Birth, self.lineEdit_First_Name)
        QWidget.setTabOrder(self.lineEdit_First_Name, self.lineEdit_Last_Name)
        QWidget.setTabOrder(self.lineEdit_Last_Name, self.lineEdit_Password)
        QWidget.setTabOrder(self.lineEdit_Password, self.lineEdit_Password_Confirmation)
        QWidget.setTabOrder(self.lineEdit_Password_Confirmation, self.AddButton)

        self.retranslateUi(FirstUsePage)

        self.comboBox_Gender.setCurrentIndex(-1)
        self.comboBoxLanguage.setCurrentIndex(-1)


        QMetaObject.connectSlotsByName(FirstUsePage)
    # setupUi

    def retranslateUi(self, FirstUsePage):
        FirstUsePage.setWindowTitle(QCoreApplication.translate("FirstUsePage", u"First Use Page", None))
        self.ResetButton.setText(QCoreApplication.translate("FirstUsePage", u"Reset", None))
        self.AddButton.setText(QCoreApplication.translate("FirstUsePage", u"Add Admin", None))
        self.label_Last_Name.setText(QCoreApplication.translate("FirstUsePage", u"Last Name:", None))
        self.comboBox_Gender.setItemText(0, QCoreApplication.translate("FirstUsePage", u"Male", None))
        self.comboBox_Gender.setItemText(1, QCoreApplication.translate("FirstUsePage", u"Female", None))
        self.comboBox_Gender.setItemText(2, QCoreApplication.translate("FirstUsePage", u"Other", None))

        self.label_First_Name.setText(QCoreApplication.translate("FirstUsePage", u"First Name:", None))
        self.label_Email.setText(QCoreApplication.translate("FirstUsePage", u"Email:", None))
        self.label_Date_Of_Birth.setText(QCoreApplication.translate("FirstUsePage", u"Date Of Birth:", None))
        self.label_Gender.setText(QCoreApplication.translate("FirstUsePage", u"Gender:", None))
        self.label_Password_Confirmation.setText(QCoreApplication.translate("FirstUsePage", u"Password Confirmation:", None))
        self.label_Password.setText(QCoreApplication.translate("FirstUsePage", u"Password:", None))
        self.label_Username.setText(QCoreApplication.translate("FirstUsePage", u"Username:", None))
        self.error_Email.setText(QCoreApplication.translate("FirstUsePage", u"error_Email", None))
        self.error_Username.setText(QCoreApplication.translate("FirstUsePage", u"error_Username", None))
        self.error_First_Name.setText(QCoreApplication.translate("FirstUsePage", u"error_First_Name", None))
        self.error_Last_Name.setText(QCoreApplication.translate("FirstUsePage", u"error_Last_Name", None))
        self.error_Password.setText(QCoreApplication.translate("FirstUsePage", u"error_Password", None))
        self.error_Password_Confirmation.setText(QCoreApplication.translate("FirstUsePage", u"error_Password_Confirmation", None))
        self.error_Gender.setText(QCoreApplication.translate("FirstUsePage", u"error_Gender", None))
        self.comboBoxLanguage.setItemText(0, QCoreApplication.translate("FirstUsePage", u"English", None))
        self.comboBoxLanguage.setItemText(1, QCoreApplication.translate("FirstUsePage", u"\u05e2\u05d1\u05e8\u05d9\u05ea", None))

        self.comboBoxLanguage.setCurrentText("")
        self.label_Register_New_Physiotherapist.setText(QCoreApplication.translate("FirstUsePage", u"First Use Page", None))
    # retranslateUi

