# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'RegisterNewPhysiotherapist.ui'
##
## Created by: Qt User Interface Compiler version 6.8.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QDateEdit,
    QLabel, QLineEdit, QMainWindow, QMenuBar,
    QPushButton, QSizePolicy, QStatusBar, QWidget)

class Ui_RegisterNewPhysiotherapist(object):
    def setupUi(self, RegisterNewPhysiotherapist):
        if not RegisterNewPhysiotherapist.objectName():
            RegisterNewPhysiotherapist.setObjectName(u"RegisterNewPhysiotherapist")
        RegisterNewPhysiotherapist.resize(481, 560)
        self.centralwidget = QWidget(RegisterNewPhysiotherapist)
        self.centralwidget.setObjectName(u"centralwidget")
        self.label_Register_New_Physiotherapist = QLabel(self.centralwidget)
        self.label_Register_New_Physiotherapist.setObjectName(u"label_Register_New_Physiotherapist")
        self.label_Register_New_Physiotherapist.setGeometry(QRect(20, 10, 441, 41))
        font = QFont()
        font.setPointSize(9)
        font.setBold(True)
        self.label_Register_New_Physiotherapist.setFont(font)
        self.LogOffButton = QPushButton(self.centralwidget)
        self.LogOffButton.setObjectName(u"LogOffButton")
        self.LogOffButton.setGeometry(QRect(320, 490, 75, 24))
        self.LogOffButton.setCursor(QCursor(Qt.CursorShape.OpenHandCursor))
        self.AddButton = QPushButton(self.centralwidget)
        self.AddButton.setObjectName(u"AddButton")
        self.AddButton.setGeometry(QRect(160, 430, 151, 31))
        self.AddButton.setCursor(QCursor(Qt.CursorShape.OpenHandCursor))
        self.ReturnButton = QPushButton(self.centralwidget)
        self.ReturnButton.setObjectName(u"ReturnButton")
        self.ReturnButton.setGeometry(QRect(90, 490, 75, 24))
        self.ReturnButton.setCursor(QCursor(Qt.CursorShape.OpenHandCursor))
        self.label_Is_Admin = QLabel(self.centralwidget)
        self.label_Is_Admin.setObjectName(u"label_Is_Admin")
        self.label_Is_Admin.setGeometry(QRect(90, 390, 300, 21))
        self.label_Last_Name = QLabel(self.centralwidget)
        self.label_Last_Name.setObjectName(u"label_Last_Name")
        self.label_Last_Name.setGeometry(QRect(90, 270, 300, 21))
        self.lineEdit_First_Name = QLineEdit(self.centralwidget)
        self.lineEdit_First_Name.setObjectName(u"lineEdit_First_Name")
        self.lineEdit_First_Name.setGeometry(QRect(230, 230, 160, 21))
        self.lineEdit_Email = QLineEdit(self.centralwidget)
        self.lineEdit_Email.setObjectName(u"lineEdit_Email")
        self.lineEdit_Email.setGeometry(QRect(230, 70, 160, 21))
        self.comboBox_Gender = QComboBox(self.centralwidget)
        self.comboBox_Gender.addItem("")
        self.comboBox_Gender.addItem("")
        self.comboBox_Gender.addItem("")
        self.comboBox_Gender.setObjectName(u"comboBox_Gender")
        self.comboBox_Gender.setGeometry(QRect(230, 150, 160, 21))
        self.comboBox_Gender.setCursor(QCursor(Qt.CursorShape.OpenHandCursor))
        self.label_First_Name = QLabel(self.centralwidget)
        self.label_First_Name.setObjectName(u"label_First_Name")
        self.label_First_Name.setGeometry(QRect(90, 230, 300, 21))
        self.label_Email = QLabel(self.centralwidget)
        self.label_Email.setObjectName(u"label_Email")
        self.label_Email.setGeometry(QRect(90, 70, 300, 21))
        self.dateEdit_Date_Of_Birth = QDateEdit(self.centralwidget)
        self.dateEdit_Date_Of_Birth.setObjectName(u"dateEdit_Date_Of_Birth")
        self.dateEdit_Date_Of_Birth.setEnabled(True)
        self.dateEdit_Date_Of_Birth.setGeometry(QRect(230, 190, 160, 21))
        self.dateEdit_Date_Of_Birth.setCursor(QCursor(Qt.CursorShape.OpenHandCursor))
        self.dateEdit_Date_Of_Birth.setMouseTracking(False)
        self.dateEdit_Date_Of_Birth.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.dateEdit_Date_Of_Birth.setCalendarPopup(True)
        self.label_Date_Of_Birth = QLabel(self.centralwidget)
        self.label_Date_Of_Birth.setObjectName(u"label_Date_Of_Birth")
        self.label_Date_Of_Birth.setGeometry(QRect(90, 190, 300, 21))
        self.label_Gender = QLabel(self.centralwidget)
        self.label_Gender.setObjectName(u"label_Gender")
        self.label_Gender.setGeometry(QRect(90, 150, 300, 21))
        self.lineEdit_Last_Name = QLineEdit(self.centralwidget)
        self.lineEdit_Last_Name.setObjectName(u"lineEdit_Last_Name")
        self.lineEdit_Last_Name.setGeometry(QRect(230, 270, 160, 21))
        self.lineEdit_Password_Confirmation = QLineEdit(self.centralwidget)
        self.lineEdit_Password_Confirmation.setObjectName(u"lineEdit_Password_Confirmation")
        self.lineEdit_Password_Confirmation.setGeometry(QRect(230, 350, 160, 21))
        self.label_Password_Confirmation = QLabel(self.centralwidget)
        self.label_Password_Confirmation.setObjectName(u"label_Password_Confirmation")
        self.label_Password_Confirmation.setGeometry(QRect(90, 350, 300, 21))
        self.lineEdit_Password = QLineEdit(self.centralwidget)
        self.lineEdit_Password.setObjectName(u"lineEdit_Password")
        self.lineEdit_Password.setGeometry(QRect(230, 310, 160, 21))
        self.label_Password = QLabel(self.centralwidget)
        self.label_Password.setObjectName(u"label_Password")
        self.label_Password.setGeometry(QRect(90, 310, 300, 21))
        self.checkBox_Is_Admin = QCheckBox(self.centralwidget)
        self.checkBox_Is_Admin.setObjectName(u"checkBox_Is_Admin")
        self.checkBox_Is_Admin.setGeometry(QRect(230, 390, 16, 21))
        self.checkBox_Is_Admin.setCursor(QCursor(Qt.CursorShape.ClosedHandCursor))
        self.label_Username = QLabel(self.centralwidget)
        self.label_Username.setObjectName(u"label_Username")
        self.label_Username.setGeometry(QRect(90, 110, 300, 21))
        self.lineEdit_Username = QLineEdit(self.centralwidget)
        self.lineEdit_Username.setObjectName(u"lineEdit_Username")
        self.lineEdit_Username.setGeometry(QRect(230, 110, 160, 21))
        self.error_Email = QLabel(self.centralwidget)
        self.error_Email.setObjectName(u"error_Email")
        self.error_Email.setGeometry(QRect(239, 90, 200, 16))
        self.error_Username = QLabel(self.centralwidget)
        self.error_Username.setObjectName(u"error_Username")
        self.error_Username.setGeometry(QRect(239, 130, 200, 16))
        self.error_Gender = QLabel(self.centralwidget)
        self.error_Gender.setObjectName(u"error_Gender")
        self.error_Gender.setGeometry(QRect(239, 170, 200, 16))
        self.error_First_Name = QLabel(self.centralwidget)
        self.error_First_Name.setObjectName(u"error_First_Name")
        self.error_First_Name.setGeometry(QRect(239, 250, 200, 16))
        self.error_Last_Name = QLabel(self.centralwidget)
        self.error_Last_Name.setObjectName(u"error_Last_Name")
        self.error_Last_Name.setGeometry(QRect(239, 290, 200, 16))
        self.error_Password = QLabel(self.centralwidget)
        self.error_Password.setObjectName(u"error_Password")
        self.error_Password.setGeometry(QRect(239, 330, 200, 16))
        self.error_Password_Confirmation = QLabel(self.centralwidget)
        self.error_Password_Confirmation.setObjectName(u"error_Password_Confirmation")
        self.error_Password_Confirmation.setGeometry(QRect(239, 370, 200, 16))
        self.comboBoxLanguage = QComboBox(self.centralwidget)
        self.comboBoxLanguage.addItem("")
        self.comboBoxLanguage.addItem("")
        self.comboBoxLanguage.setObjectName(u"comboBoxLanguage")
        self.comboBoxLanguage.setGeometry(QRect(400, 10, 68, 22))
        self.comboBoxLanguage.setCursor(QCursor(Qt.CursorShape.OpenHandCursor))
        RegisterNewPhysiotherapist.setCentralWidget(self.centralwidget)
        self.label_Username.raise_()
        self.label_Email.raise_()
        self.label_Register_New_Physiotherapist.raise_()
        self.LogOffButton.raise_()
        self.AddButton.raise_()
        self.ReturnButton.raise_()
        self.label_Is_Admin.raise_()
        self.label_Last_Name.raise_()
        self.label_First_Name.raise_()
        self.label_Date_Of_Birth.raise_()
        self.label_Gender.raise_()
        self.label_Password_Confirmation.raise_()
        self.label_Password.raise_()
        self.error_Email.raise_()
        self.error_Username.raise_()
        self.error_Gender.raise_()
        self.error_First_Name.raise_()
        self.error_Last_Name.raise_()
        self.error_Password.raise_()
        self.error_Password_Confirmation.raise_()
        self.comboBoxLanguage.raise_()
        self.lineEdit_Email.raise_()
        self.lineEdit_First_Name.raise_()
        self.lineEdit_Last_Name.raise_()
        self.lineEdit_Password.raise_()
        self.lineEdit_Password_Confirmation.raise_()
        self.lineEdit_Username.raise_()
        self.comboBox_Gender.raise_()
        self.dateEdit_Date_Of_Birth.raise_()
        self.checkBox_Is_Admin.raise_()
        self.menubar = QMenuBar(RegisterNewPhysiotherapist)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 481, 22))
        RegisterNewPhysiotherapist.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(RegisterNewPhysiotherapist)
        self.statusbar.setObjectName(u"statusbar")
        RegisterNewPhysiotherapist.setStatusBar(self.statusbar)
        QWidget.setTabOrder(self.lineEdit_Email, self.lineEdit_Username)
        QWidget.setTabOrder(self.lineEdit_Username, self.comboBox_Gender)
        QWidget.setTabOrder(self.comboBox_Gender, self.dateEdit_Date_Of_Birth)
        QWidget.setTabOrder(self.dateEdit_Date_Of_Birth, self.lineEdit_First_Name)
        QWidget.setTabOrder(self.lineEdit_First_Name, self.lineEdit_Last_Name)
        QWidget.setTabOrder(self.lineEdit_Last_Name, self.lineEdit_Password)
        QWidget.setTabOrder(self.lineEdit_Password, self.lineEdit_Password_Confirmation)
        QWidget.setTabOrder(self.lineEdit_Password_Confirmation, self.checkBox_Is_Admin)
        QWidget.setTabOrder(self.checkBox_Is_Admin, self.AddButton)
        QWidget.setTabOrder(self.AddButton, self.ReturnButton)
        QWidget.setTabOrder(self.ReturnButton, self.LogOffButton)

        self.retranslateUi(RegisterNewPhysiotherapist)

        self.comboBox_Gender.setCurrentIndex(-1)
        self.comboBoxLanguage.setCurrentIndex(-1)


        QMetaObject.connectSlotsByName(RegisterNewPhysiotherapist)
    # setupUi

    def retranslateUi(self, RegisterNewPhysiotherapist):
        RegisterNewPhysiotherapist.setWindowTitle(QCoreApplication.translate("RegisterNewPhysiotherapist", u"Register New Physiotherapist", None))
        self.label_Register_New_Physiotherapist.setText(QCoreApplication.translate("RegisterNewPhysiotherapist", u"Register New Physiotherapist", None))
        self.LogOffButton.setText(QCoreApplication.translate("RegisterNewPhysiotherapist", u"Log Off", None))
        self.AddButton.setText(QCoreApplication.translate("RegisterNewPhysiotherapist", u"Add New Physiotherapist", None))
        self.ReturnButton.setText(QCoreApplication.translate("RegisterNewPhysiotherapist", u"Return", None))
        self.label_Is_Admin.setText(QCoreApplication.translate("RegisterNewPhysiotherapist", u"Is Admin:", None))
        self.label_Last_Name.setText(QCoreApplication.translate("RegisterNewPhysiotherapist", u"Last Name:", None))
        self.comboBox_Gender.setItemText(0, QCoreApplication.translate("RegisterNewPhysiotherapist", u"Male", None))
        self.comboBox_Gender.setItemText(1, QCoreApplication.translate("RegisterNewPhysiotherapist", u"Female", None))
        self.comboBox_Gender.setItemText(2, QCoreApplication.translate("RegisterNewPhysiotherapist", u"Other", None))

        self.label_First_Name.setText(QCoreApplication.translate("RegisterNewPhysiotherapist", u"First Name:", None))
        self.label_Email.setText(QCoreApplication.translate("RegisterNewPhysiotherapist", u"Email:", None))
        self.label_Date_Of_Birth.setText(QCoreApplication.translate("RegisterNewPhysiotherapist", u"Date Of Birth:", None))
        self.label_Gender.setText(QCoreApplication.translate("RegisterNewPhysiotherapist", u"Gender:", None))
        self.label_Password_Confirmation.setText(QCoreApplication.translate("RegisterNewPhysiotherapist", u"Password Confirmation:", None))
        self.label_Password.setText(QCoreApplication.translate("RegisterNewPhysiotherapist", u"Password:", None))
        self.checkBox_Is_Admin.setText("")
        self.label_Username.setText(QCoreApplication.translate("RegisterNewPhysiotherapist", u"Username:", None))
        self.error_Email.setText(QCoreApplication.translate("RegisterNewPhysiotherapist", u"error_Email", None))
        self.error_Username.setText(QCoreApplication.translate("RegisterNewPhysiotherapist", u"error_Username", None))
        self.error_Gender.setText(QCoreApplication.translate("RegisterNewPhysiotherapist", u"error_Gender", None))
        self.error_First_Name.setText(QCoreApplication.translate("RegisterNewPhysiotherapist", u"error_First_Name", None))
        self.error_Last_Name.setText(QCoreApplication.translate("RegisterNewPhysiotherapist", u"error_Last_Name", None))
        self.error_Password.setText(QCoreApplication.translate("RegisterNewPhysiotherapist", u"error_Password", None))
        self.error_Password_Confirmation.setText(QCoreApplication.translate("RegisterNewPhysiotherapist", u"error_Password_Confirmation", None))
        self.comboBoxLanguage.setItemText(0, QCoreApplication.translate("RegisterNewPhysiotherapist", u"English", None))
        self.comboBoxLanguage.setItemText(1, QCoreApplication.translate("RegisterNewPhysiotherapist", u"\u05e2\u05d1\u05e8\u05d9\u05ea", None))

        self.comboBoxLanguage.setCurrentText("")
    # retranslateUi

